bash/Dockerfile
For php scriptfiles we need more libraries in order to fulfill certain checking tasks.
It is to be reminded, that those additional libraries add more time for the docker container to
start up, increasing the time the Server needs to respond.
=> Add MCrypt Library to Bash/php checker environment

ws/build.gradle, ws/src/main/scala/de/thm/ii/fbs/util/DateParser.scala, ws/src/test/scala/de/thm/ii/fbs/util/DateParserTest.scala
Implemented first test for WS.
The test tests the unit class DateParser that supposes to transform date, represented as string, to java.time LocalDate object.
I have removed some date formats that we will never use in the application.
=> implemented first test

docker-compose.yml, ws/build.gradle, ws/src/main/resources/application.yml, ws/src/main/scala/de/thm/ii/fbs/services/checker/RemoteCheckerService.scala
This allows to disable TLS-Certificate validation for requests to the master runner. And thus allows to inform the master runner of a new submission even when it uses a self-signed certificate.
=> Fix TLS certificate validation for requests to the Master Runner

build.gradle, web-gui/build.gradle
Fix copy ws to enable inclusion of the web-gui in ws when build with `gradle dist`.
=> Fix copy ws

ws/src/main/scala/de/thm/ii/fbs/controller/LoginController.scala
This fixes #445.
Das Problem war, dass bei Verwendung des CAS-Logins der `JSESSIONID` Cookie gesetzt wird, welcher bei Verwendung des Konferenz-Features Probleme mit der Autorisierung der Websocket-Verbindungen verursacht.
=> Fix conference with cas login

web-gui/src/app/app.module.ts, web-gui/src/app/service/auth.service.ts
We got the hint that the users role is only updated after he logout and in again.
I wrote a hook that looks in all response messages from HttpClient, retrieves the JWT token
that is located in the response (if exists) and stores the new token by overwriting the old one.
Since the token stores the users role, it should be updated with any interaction with the server that uses the HttpClient.
=> Renew token

master-runner/src/main/scala/de/thm/ii/fbs/services/ExtendedResultsService.scala, master-runner/src/main/scala/de/thm/ii/fbs/services/runner/SQLRunnerService.scala, master-runner/src/main/scala/de/thm/ii/fbs/verticles/runner/SqlRunnerVerticle.scala, master-runner/swagger.yml, swagger.yml, ws/src/main/resources/fbs.sql, ws/src/main/scala/de/thm/ii/fbs/controller/ResultController.scala, ws/src/main/scala/de/thm/ii/fbs/controller/SubmissionController.scala, ws/src/main/scala/de/thm/ii/fbs/model/CheckResult.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/SubmissionService.scala
I have added the extended runner information as described in  #466 (Currently only for the SQL Runner).
The requests for the submissions (e.g.: `/api/v1/{uid}/courses/{cid}/tasks/{tid}/submissions`) now contain, if you have the correct permissions, the extended information (if there are none or you don't have the permissions, these are `null`).
=>  master-runner additional information

ws/src/main/scala/de/thm/ii/fbs/model/Participant.scala, ws/src/main/scala/de/thm/ii/fbs/services/conferences/conference/BBBConference.scala
After reviewing the feedback systems functionality with a group of students, it became clear that being invisible upon entering and not seeing oneself is unintuitive for many users and raises concern if it functions properly.
=> Change: Make all Conferences and Users public by default

swagger.yml, web-gui/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts, web-gui/src/app/model/Task.ts, ws/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala, ws/src/main/scala/de/thm/ii/fbs/model/Task.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/TaskService.scala, ws/src/main/scala/de/thm/ii/fbs/util/ISO8601.scala
This pull request changes the api format of the deadline from a Unix timestamp to iso 8601.
In addition, the time of the deadline is now also stored in the database, not just the date.
Closes #482
=> Change deadline format from unix time to iso 8601

.travis.yml
Hopefully fixes coveralls not associating coverage reports with the dev branch.
=> Fix coveralls branch

ws/src/main/scala/de/thm/ii/fbs/services/conferences/BBBService.scala
This PR fixes the encoding when creating Big Blue Button join URLs and therefore makes it possible for users with speacial characters like `'` in their names to join conferences.
=> Fix bbb name encoding

ci/docker-deploy.sh
resolves #507 
Due to the rate limits introduced by Docker Hub, it is necessary to log in before creating the Docker containers, otherwise required containers will not be downloaded.
=> Deployment error

ws/src/main/scala/de/thm/ii/fbs/services/persistance/CourseResultService.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/EvaluationContainerService.scala
Fixes an error in the calculation of course results. This error occurs when there is a comma (`,`) in the description of a task.
=> Course evaluation backend fix

.github/workflows/ci-cd.yml
The deployment script must be executed with `bash` and not with `sh`.
---
Fix for #555
=> [CI/CD] run script with bash

swagger.yml, ws/src/main/scala/de/thm/ii/fbs/controller/AnalysisController.scala, ws/src/main/scala/de/thm/ii/fbs/model/AnalysisCourseResult.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistence/CourseResultService.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistence/StorageService.scala
Adds a route to get all the results for a task (`/analysis/courses/{cid}/results/{tid}`). These do not contain any personal user information as they are only to be used for data analysis.
=> Add analysis routes

web-gui/src/app/app.module.ts
In the PR #573 a proxy configuration was pushed by mistake which should only be present in the development process.
=> [Bug] Remove development configuration from proxy setup

ws/src/main/scala/de/thm/ii/fbs/services/classroom/ClassroomService.scala
Switch to default Spring RestTemplate instead of Apache implementation.
The default RestTemplate accepts the valid SSL certificate. Which is fine, because it is a valid, signed CA-issued certificate.
=> Fix classroom HTTPS call

docker-compose.yml
Remove port mapping from `docker-compose.yaml` to prevent regressions during deployment.
=> Remove exposed ports from mysql container

.github/CODEOWNERS
The default owners must be defined at the beginning of the file (see [github docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file)).
=> [CODEOWNERS] move default owners to the top

.github/workflows/add-issue-to-project.yml
The current used version (Copied from the github-docs) does not exsist.
---
follow up #741
=> [CI] Update `tibdex/github-app-token` version

build.gradle
For testing, before the FBS is built, the command `./gradlew clean` should be executed and the folder `modules/fbs-core/api/src/main/resources/static` should be deleted.
---
resolves #743
=>  [API] The API package building process is executed before the web package is copied

.github/pr-title-checker-config.json, .github/workflows/pull-request-verifier.yml
This PR adds a CI/CD that checks the title of a pull request and fails if it starts with `i<number>` or `<number>`. This check is to prevent PRs with the default name (name of the branch) from being merged (as happened in #775 and #768), as this would make for an unpleasant commit message.
=> [CI/CD]  Add a Pull request verifier

.github/release.yml
Adding a configuration for the github relase notes (see [Github Docs](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes))
=> add release notes configuration

modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.html, modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts, modules/fbs-core/web/src/app/model/Task.ts, modules/fbs-core/web/src/app/page-components/course-detail/task-preview/task-preview.component.html
resolves #704 
If the task is mandatory, the user sees this:
and this, if it's bonus:
While creating or updating a task, the lecturer can choose "Pflicht" or "Bonus":
=> [Web] Mark tasks as "mandatory", "bonus/additional", etc.

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/util/JsonWrapper.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/util/JsonWrapperTest.scala
The implementation of the JSON Warpper had a bug that converts `null` as the default value of the data type instead of None (e.g. a call to the function `.asText` would convert `null` to `Some('null')`, causing the error described in #883).
---
resolves #883
=> [API] Parse JSON null values as None

runtime-images/bash/Dockerfile
follow up #1008 which updates php to version 8
=> build(deps): bump php8-pecl-mcrypt from 7 to 8 in /runtime-images/bash

.github/workflows/deploy-to-dockerhub.yml
This pr changes the branch name used to generate the docker tag to the name of the branch that triggered this workflow, rather than the branch name of this workflow, which is always `dev` (the default branch).
---
follow up #841
=> ci(deploy-to-dockerhub): use correct branch name for tag generation

modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/SemanticAstComparator.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/transformers/DebugTransformer.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/transformers/DivisionReplacingTransformer.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/transformers/ExponentTransformer.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/transformers/NeutralElementTransformer.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/SemanticAstComparatorTest.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/transformers/DebugTransformerTest.kt
I'm currently unhappy with the logic i used to instanciate the transformers for the `ChainTransformer` but I think it is better then passing `transformerConfig` to every Transformer. If anyone has a better idea let me know.
---
closes #1166
=> [Math-Parser] Add comparator support for exponent laws

runtime-images/bash/Dockerfile
Alpine 3.17 appears to have [removed](https://pkgs.alpinelinux.org/packages?name=php8-pecl-mcrypt&branch=v3.17&repo=&arch=&maintainer=) the `php8-pecl-mcrypt` package. This is just a short term solution to prevent the CI from failing. In the long term an alternative for the package should be found.
=> [Bash] Pin bash image to alpine 3.16

modules/fbs-core/web/package-lock.json
**The following updates are included in this PR:**
- [engine.io](https://github.com/thm-mni-ii/feedbacksystem/commit/6db9507132ed3d3768a2c0534475623cf6fce9f2) from 6.2.1 to 6.4.2
- [socket.io](https://github.com/thm-mni-ii/feedbacksystem/commit/6db9507132ed3d3768a2c0534475623cf6fce9f2) from 4.5.1 to 4.6.1
- [@braintree/sanitize-url](https://github.com/thm-mni-ii/feedbacksystem/commit/938113b29109e9b94b62602c25ea736c363569a3) from 6.0.0 to 6.0.2.
- [socket.io-parser](https://github.com/thm-mni-ii/feedbacksystem/commit/29d4d374c539974c6b6b355b92e4c31309269837)
- [http-cache-semantics](https://github.com/thm-mni-ii/feedbacksystem/commit/1d8a20a41340a56a2fd4c2be7c9adab6a1886f14) from 4.1.0 to 4.1.1.
- [ua-parser-js](https://github.com/thm-mni-ii/feedbacksystem/commit/306ca34e93ef6e9121e70c9960 …
=> Update multiple npm dependecies

.github/actions/retry-codecov/action.yml
In #1363, the `continue-on-error` option was added to prevent the job from failing if a retry was performed, but this leads to the bug that no retries were performed because the `conclusion` of the previous step was always `success`. To prevent this, the output `outcome` is now used (see [Github Docs](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context) for more information).
---
- follow up #1363
=> ci(retry-codecov): Fixes an error that caused retry not to be executed

modules/fbs-core/web/src/app/model/sql_playground/Routine.ts, modules/fbs-core/web/src/app/page-components/sql-playground/db-scheme/db-scheme-routines/db-scheme-routines.component.html, modules/fbs-core/web/src/app/page-components/sql-playground/db-scheme/db-scheme.component.scss, modules/fbs-core/web/src/i18n/de.ts, modules/fbs-core/web/src/i18n/en.ts, modules/fbs-core/web/src/styles.scss, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/db/PsqlOperationsService.scala
=> [Playground] show parameters for stored procedures/functions

docker-compose.yml
Bug solved, log in is now reachable
=> adding mongodb and minio to core depencies in docker-compose.yml

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/GroupController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/GroupRegistrationController.scala
=> fix(core): update permission checks for course group information

modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/controller/v2/IntegrationController.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/model/v2/misc/Integration.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/misc/IntegrationService.kt, modules/fbs-core/api/src/main/resources/application.yml, modules/fbs-core/web/src/app/model/Integration.ts, modules/fbs-core/web/src/app/page-components/fbs-modelling/fbs-modelling.component.html, modules/fbs-core/web/src/app/page-components/fbs-modelling/fbs-modelling.component.ts, modules/fbs-core/web/src/app/service/integration.service.ts
=> feat(core): add configurable modelling tool url
