thm-mni-ii/feedbacksystem

web-gui/package-lock.json, ws/src/main/scala/de/thm/ii/submissioncheck/controller/CourseController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/model/User.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/CourseService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TaskService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/UserService.scala
Provides a PR for a first user-role-system.
=> #45 implement role system

ws/src/main/resources/application.properties, ws/src/main/resources/init.sql, ws/src/main/scala/de/thm/ii/submissioncheck/controller/CourseController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/controller/TaskController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/misc/JsonParser.scala, ws/src/main/scala/de/thm/ii/submissioncheck/security/Secrets.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/CourseService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/StorageService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TaskService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TokenService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/UserService.scala
Provide Changes defined in ticket #57
=> #57 rest courses tasks

web-gui/src/app/service/database.service.ts
Created routes for db and returns fake json data
=> Routes with fake data

ws/src/main/resources/init.sql, ws/src/main/scala/de/thm/ii/submissioncheck/controller/TaskController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TaskService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TestsystemService.scala
provide new DB and listen on testsystem specific topics
=> #61 implement testsystems ws

ws/src/main/scala/de/thm/ii/submissioncheck/controller/TaskController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/StorageService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TaskService.scala
Use Upload URL, no base64 string.
=> #70 all submissions

web-gui/src/app/modules/student/student-course/student-course-dialog/student-course-dialog.component.html, web-gui/src/app/modules/student/student-course/student-course-dialog/student-course-dialog.component.ts, web-gui/src/app/modules/student/student-course/student-course.component.html, web-gui/src/app/modules/student/student-course/student-course.component.ts, web-gui/src/app/service/database.service.ts
=> #94 show tasks

web-gui/src/app/app.module.ts, web-gui/src/app/modules/student/student-course/student-course.component.html, web-gui/src/app/modules/student/student-course/student-course.component.ts, web-gui/src/app/service/database.service.ts
=> Submit task

ws/src/main/scala/de/thm/ii/submissioncheck/controller/CourseController.scala
We need to fix the consumes field otherwise the request causes strange TypeMissmatch Exceptions.
=> Hot-Fix: Consumes JSON causes Exception

web-gui/src/app/modules/student/student-dashboard/student-dashboard.component.html, web-gui/src/app/modules/student/student-dashboard/student-dashboard.component.spec.ts, web-gui/src/app/modules/student/student-dashboard/student-dashboard.component.ts, web-gui/src/app/modules/student/student-routing.module.ts, web-gui/src/app/modules/student/student-start/student-start.component.html, web-gui/src/app/modules/student/student.module.ts, web-gui/src/app/service/auth.service.ts, web-gui/src/app/service/database.service.ts
=> #100 dashboard user

web-gui/src/app/modules/material-components/material-components.module.ts, web-gui/src/app/modules/professor/prof-courses/prof-courses.component.html, web-gui/src/app/modules/professor/prof-courses/prof-courses.component.scss, web-gui/src/app/modules/professor/prof-courses/prof-courses.component.spec.ts, web-gui/src/app/modules/professor/prof-courses/prof-courses.component.ts, web-gui/src/app/modules/professor/prof-start/prof-start.component.html, web-gui/src/app/modules/professor/prof-start/prof-start.component.scss, web-gui/src/app/modules/professor/prof-start/prof-start.component.ts, web-gui/src/app/modules/professor/professor-routing.module.ts, web-gui/src/app/modules/professor/professor.module.ts, web-gui/src/app/service/auth.service.ts
=> #105 manage courses

web-gui/src/app/modules/student/student-course/student-course.component.html, web-gui/src/app/modules/student/student-course/student-course.component.ts, web-gui/src/app/service/database.service.ts
Shows result of user submission
=> #97 submission result

ws/src/main/scala/de/thm/ii/submissioncheck/controller/TaskController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/controller/TestsystemController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/model/Testsystem.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TestsystemService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/UserService.scala
Force to only provide files if token is valid
=> #92 jwt token secrettoken checker

ws/src/main/scala/de/thm/ii/submissioncheck/controller/UserController.scala
@Phpp1010 Thank you for your issue. I changed it now.
=> #116: change 'GET /users/last_login' to 'GET /users' 

.travis.yml, py-test/request.py, py-test/sample.sql, py-test/travis-fix.sh, ws/src/main/scala/de/thm/ii/submissioncheck/controller/TaskController.scala
Provide solution to run python unittest on running spring boot application
=> #89: Provide solution to run python unittest

web-gui/src/app/modules/professor/prof-courses/prof-courses.component.html, web-gui/src/app/modules/professor/prof-courses/prof-courses.component.ts, web-gui/src/app/modules/professor/prof-courses/prof-new-task-dialog/prof-new-task-dialog.component.html, web-gui/src/app/modules/professor/prof-courses/prof-new-task-dialog/prof-new-task-dialog.component.scss, web-gui/src/app/modules/professor/prof-courses/prof-new-task-dialog/prof-new-task-dialog.component.spec.ts, web-gui/src/app/modules/professor/prof-courses/prof-new-task-dialog/prof-new-task-dialog.component.ts, web-gui/src/app/modules/professor/professor.module.ts, web-gui/src/app/service/database.service.ts
Lecturer has CRUD functionality for tasks
=> #18 lecturer manage task

web-gui/src/app/service/database.service.ts
File upload works on task update
=> Upload file for task update

ws/src/main/scala/de/thm/ii/submissioncheck/controller/TaskController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/CourseService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TaskService.scala
Provide result infos in task and courses to get current submission state for user
=> #160 result info task

web-gui/package-lock.json, web-gui/package.json, web-gui/src/app/app.module.ts, web-gui/src/app/components/login/login.component.html, web-gui/src/app/components/login/login.component.scss, web-gui/src/app/components/login/login.component.ts
=> Cas login2

web-gui/src/app/components/courses/grant-tutor/grant-tutor.component.ts
Gives only courses back where docent have docent rights in course.
=> Fix gives back right courses

web-gui/src/app/app.module.ts, web-gui/src/app/components/courses/detail-course/detail-course.component.html, web-gui/src/app/components/courses/detail-course/detail-course.component.ts, web-gui/src/app/components/login/login.component.ts, web-gui/src/app/guards/admin.guard.ts, web-gui/src/app/guards/auth.guard.ts, web-gui/src/app/guards/docent.guard.ts, web-gui/src/app/guards/is-docent.guard.ts, web-gui/src/app/guards/moderator.guard.ts
=> Feature routing link

web-gui/src/app/components/users/change-passwd/change-passwd.component.html, web-gui/src/app/components/users/change-passwd/change-passwd.component.ts
=> fix to password type

web-gui/src/app/app.module.ts, web-gui/src/app/components/admin/admin-user-management/admin-user-management.component.html, web-gui/src/app/components/admin/admin-user-management/admin-user-management.component.scss, web-gui/src/app/components/admin/admin-user-management/admin-user-management.component.ts, web-gui/src/app/components/admin/admin-user-management/create-guest-user-dialog.html, web-gui/src/app/components/admin/admin-user-management/create-guest-user-dialog.scss
* Use dialog to display guest user form
* added form validation
* changed alternating table row color to a light blue color (previously light gray)
=> restyled users management

bash/similarity-tester-master/clean_up.sh, bash/similarity-tester-master/plagiat_check_folders.sh, bash/similarity-tester-master/run_check.sh
- integrate config from other test (#324)
=> better options, some ideas of preparing data / #324

.gitignore, docker-compose.yml, docker-config/ws/init.sql, secrettoken-checker/Dockerfile, secrettoken-checker/src/main/scala/de/thm/ii/submissioncheck/FileOperations.scala, secrettoken-checker/src/main/scala/de/thm/ii/submissioncheck/checker/BaseChecker.scala, secrettoken-checker/src/main/scala/de/thm/ii/submissioncheck/checker/PlagiatCheckExec.scala, secrettoken-checker/src/main/scala/de/thm/ii/submissioncheck/checker/SecrettokenCheckExec.scala, web-gui/src/app/components/courses/course-tasks-overview/course-tasks-overview.component.html, web-gui/src/app/components/courses/course-tasks-overview/course-tasks-overview.component.ts, web-gui/src/app/components/courses/detail-course/course-prof-details/course-prof-details.component.html, web-gui/src/app/components/courses/detail-course/course-prof-details/course-prof-details.component.ts, web-gui/src/app/interfaces/HttpInterfaces.ts, web-gui/src/app/service/database.service.ts, ws/Dockerfile, ws/src/main/scala/de/thm/ii/submissioncheck/controller/CourseController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/controller/SubmissionController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/controller/TaskController.scala, ws/src/main/scala/de/thm/ii/submissioncheck/model/TaskExtension.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/CourseService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/StorageService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TaskExtensionService.scala, ws/src/main/scala/de/thm/ii/submissioncheck/services/TestsystemMessagesHandler.scala
- plagiarism checker creates a zip of submission where a match is detected / assumed
- zip file is sent to webservice (WS)
- the zip is display in the dashboard detail view
=> plagiarism sends zip to ws, display extended task information

web-gui/src/app/util/rx-stomp.ts, ws/src/main/scala/de/thm/ii/fbs/controller/HomeController.scala, ws/src/main/scala/de/thm/ii/fbs/controller/TestsystemController.scala, ws/src/main/scala/de/thm/ii/fbs/services/GitChecker.scala, ws/src/main/scala/de/thm/ii/fbs/services/TestsystemService.scala
* fix: white label error on /login page refresh
* change: increase WS reconnect delay from 0.2 to 2 seconds
* remove dependency to DB testsystem, setting and testsystem_setting
=> Testsystem

secrettoken-checker/Dockerfile, secrettoken-checker/build.gradle, secrettoken-checker/src/main/resources/application.conf, secrettoken-checker/src/main/scala/de/thm/ii/fbs/FileOperations.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/JsonHelper.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/SecretTokenChecker.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/checker/BaseChecker.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/checker/GitCheckExec.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/checker/GitstatsCheckExec.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/checker/HelloworldCheckExec.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/checker/MultiplechoiceCheckExec.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/checker/NodeCheckExec.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/checker/PlagiatCheckExec.scala, secrettoken-checker/src/main/scala/de/thm/ii/fbs/checker/SecrettokenCheckExec.scala, web-gui/src/app/components/courses/course-tasks-overview/course-tasks-overview.component.html, web-gui/src/app/components/courses/course-tasks-overview/course-tasks-overview.component.ts, web-gui/src/app/components/courses/detail-course/detail-course.component.html, web-gui/src/app/components/courses/detail-course/detail-course.component.ts, ws/build.gradle, ws/src/main/scala/de/thm/ii/fbs/config/WebConfig.scala, ws/src/main/scala/de/thm/ii/fbs/services/TaskService.scala, ws/src/main/scala/de/thm/ii/fbs/services/TestsystemService.scala, ws/src/main/scala/de/thm/ii/fbs/util/JsonParser.scala
=> Secrettokenchecker

web-gui/src/app/app.module.ts, web-gui/src/app/components/courses/new-course/new-course.component.html, web-gui/src/app/components/courses/new-course/new-course.component.scss, web-gui/src/app/components/courses/new-course/new-course.component.ts
Removed module end-date, private information check and module term.
Instead of a stepper there is now a simple form.
=> Restyling newCourse

web-gui/src/app/components/courses/my-courses/courses.component.html, web-gui/src/app/components/courses/my-courses/courses.component.scss
=> Changed "my courses layout"

web-gui/src/app/components/courses/detail-course/update-course-dialog/update-course-dialog.component.html, web-gui/src/app/components/courses/detail-course/update-course-dialog/update-course-dialog.component.ts, web-gui/src/app/components/courses/new-course/new-course.component.html, web-gui/src/app/components/courses/new-course/new-course.component.ts
nessesary changes because of #358
=> Adjustment of "edit course dialog" because of changes made by PR: 358

web-gui/src/app/components/admin/admin-user-management/admin-user-management.component.scss, web-gui/src/app/components/courses/course-tasks-overview/course-tasks-overview.component.html, web-gui/src/app/components/courses/course-tasks-overview/course-tasks-overview.component.scss, web-gui/src/app/components/courses/grant-docent/grant-docent.component.scss, web-gui/src/app/components/courses/import-course/import-course.component.scss, web-gui/src/app/components/courses/my-courses/courses.component.scss, web-gui/src/app/components/courses/new-course/new-course.component.scss, web-gui/src/app/components/courses/search-course/search-course.component.scss, web-gui/src/app/components/courses/task-analyze-submissions/task-analyze-submissions.component.html, web-gui/src/app/components/courses/task-analyze-submissions/task-analyze-submissions.component.scss, web-gui/src/app/components/users/change-passwd/change-passwd.component.scss
Limited the width of each page to 80%. Except for the Dashboard. closes #372
=> page width changed

master-runner/src/main/scala/de/thm/ii/fbs/services/runner/BashRunnerService.scala, master-runner/src/main/scala/de/thm/ii/fbs/types/Runner.scala, master-runner/src/main/scala/de/thm/ii/fbs/types/Submission.scala, master-runner/src/main/scala/de/thm/ii/fbs/verticles/HttpVerticle.scala, master-runner/src/main/scala/de/thm/ii/fbs/verticles/runner/BashRunnerVerticle.scala, master-runner/swagger.yml
I have adapted the points discussed (#405):
- `isInfo` removed
- Bash arguments changed
- added `ccid` to result request
=> BashRunner changes

docker-compose.yml, ws/Dockerfile, ws/src/main/resources/application.yml, ws/src/main/scala/de/thm/ii/fbs/controller/ResultController.scala, ws/src/main/scala/de/thm/ii/fbs/controller/SubmissionController.scala, ws/src/main/scala/de/thm/ii/fbs/model/CheckResult.scala, ws/src/main/scala/de/thm/ii/fbs/services/checker/RemoteChecker.scala, ws/src/main/scala/de/thm/ii/fbs/services/checker/RemoteCheckerService.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/SubmissionService.scala
At the moment there is still the problem that the Master-Runner only uses HTTP connections to send the result back, this prevents the Master-Runner from sending the result back to the feedback system which is only accessible via HTTPs.
=> Add submissions to backend

ws/src/main/scala/de/thm/ii/fbs/controller/SubmissionController.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/SubmissionService.scala
This pull request implements resubmission and fixes a bug which would allow users to access the submission results of other users.
=> Add Submission resubmission

master-runner/src/main/scala/de/thm/ii/fbs/services/runner/SQLRunnerService.scala
=> Error in the SQLRunner

ws/src/main/scala/de/thm/ii/fbs/services/security/CourseAuthService.scala
Fixes a bug in course auth service.
=> Fix course auth service

web-gui/src/app/dialogs/assign-ticket-dialog/assign-ticket-dialog.component.ts, web-gui/src/app/dialogs/inviteto-conference-dialog/inviteto-conference-dialog.component.ts, web-gui/src/app/service/classroom.service.ts, ws/src/main/scala/de/thm/ii/fbs/controller/classroom/ConferenceSTOMPController.scala
Add: Heartbeats for stomp communication to prevent websocket disconnects
Fix: Default permission for bbb conferences is Moderator privilege for everyone
=> Conference system

web-gui/src/app/util/rx-stomp.ts
Hopefully this fixes instable websocket connections due to an outdated frontend client
=> Fix: deprecated websocket client connection handler

.gitignore, ws/src/main/resources/fbs.sql, ws/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala, ws/src/main/scala/de/thm/ii/fbs/controller/CourseController.scala, ws/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/StorageService.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/SubmissionService.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/TaskService.scala
resolves #442 
Deletion should now work correctly. For this I had to adapt the database shema a little bit (see 6bb5ef0c9906f21a7e0db98935c4add70b2035af). Deleting a course works in the backend, but this is not implemented in the frontend yet.
=>  Error while deleting

ws/src/main/scala/de/thm/ii/fbs/controller/SubmissionController.scala
I allow the owner, admin, moderator, docent and tutor to access the submissions of a user.
The later two can only access the submissions if it it part of the course where they have the roles.
Fixes #467
=> allow privileged read to access submissions

master-runner/src/main/resources/config.json, master-runner/src/main/scala/de/thm/ii/fbs/services/runner/SQLRunnerService.scala, master-runner/src/main/scala/de/thm/ii/fbs/verticles/runner/SqlRunnerVerticle.scala
=> Error with multiple submissions

docker-compose.yml, master-runner/src/main/resources/config.json, master-runner/src/main/scala/de/thm/ii/fbs/services/runner/SQLRunnerService.scala, master-runner/src/main/scala/de/thm/ii/fbs/verticles/runner/SqlRunnerVerticle.scala
Fixes the bug that the SQL Runner does not execute all configuration files correctly.
If we push this version to the live server we have to adjust the docker-compose.yml there (see f7915217c1d08e0067112ea8843195a7d86a1a48)
=> Sql Runner bug fix

web-gui/src/app/app.component.ts, web-gui/src/app/model/JWTToken.ts, web-gui/src/app/service/auth.service.ts, ws/src/main/resources/application.yml, ws/src/main/scala/de/thm/ii/fbs/controller/LoginController.scala
This reduces the token expiration time to 5 Minutes and adds an automatic check to the frontend to renew the token before it expires.
=> Reduce token expiration time and add automatic token renewal

.travis.yml, README.md, build.gradle, master-runner/build.gradle, master-runner/src/test/scala/de/thm/ii/fbs/ws/PlaceholderTest.scala, ws/build.gradle
=> Add coverage

master-runner/build.gradle, master-runner/src/main/scala/de/thm/ii/fbs/services/runner/SQLRunnerService.scala
resolves #492.
The sections file for the SQL Runner can now be in json or yaml format.
=> SQL Runner section file in YAML format

web-gui/src/app/page-components/task-detail/task-detail.component.html, web-gui/src/app/page-components/task-detail/task-detail.component.ts, ws/src/main/scala/de/thm/ii/fbs/controller/SubmissionController.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/TaskService.scala
#491 
Timeformat parsing needed to be fixed once more as it cut off the time part passing only the date component to the database.
=> Add: Deadline check for tasks at frontend and backend

web-gui/src/app/page-components/course-detail/course-detail.component.html, web-gui/src/app/page-components/course-detail/course-detail.component.ts, web-gui/src/app/service/feedback-app.service.ts
This Pull Request adds a button thats allows switching to the feedback App without logging in again.
=> Add GoTo Feedback App Button

master-runner/src/main/scala/de/thm/ii/fbs/services/runner/BashRunnerService.scala
=>  Bash runner: the submission of a zip file leads to an error

web-gui/build.gradle, web-gui/package.json, web-gui/src/app/dialogs/assign-ticket-dialog/assign-ticket-dialog.component.ts, web-gui/src/app/page-components/conference/conference.component.ts, web-gui/src/app/tool-components/dropzone/dropzone.component.ts
This pr changes the angular build to productive mode. This should reduce the size of the build and improve cacheing.
=> Change to angular web-gui build mode to prod

ws/src/main/scala/de/thm/ii/fbs/util/LDAPConnector.scala
resolves #502
To uniquely identify users who have multiple organizations (Fachbereiche) I enabled the [`derefAliases`](https://www.ldaptive.org/v1/docs/guide/operations/search.html) option, this ensures that all alias entries are traced back to the original entry which means that the user only has one entry from which we then get the data. Furthermore, a better error message is now thrown if multiple entries are found (Which should actually no longer be possible for a valid uid).
=> Error when logging in via CAS

web-gui/src/app/page-components/course-detail/course-detail.component.html, web-gui/src/app/page-components/course-detail/course-results/course-results.component.html, web-gui/src/app/page-components/course-detail/course-results/course-results.component.scss, web-gui/src/app/tool-components/participants/participants.component.html, web-gui/src/app/tool-components/participants/participants.component.ts
Admin can now see the menu in course-detail without registering for the course.
Fixed the icons in course-result table and added a legend.
=> menu-bar in course-detail, icon and legend in course-result

web-gui/src/app/page-components/task-detail/task-detail.component.ts
set time to 5 seconds and changed text of snackbar
=> Spinner time

web-gui/src/app/page-components/sidebar/sidebar.component.html, web-gui/src/app/page-components/sidebar/sidebar.component.ts
added link to Feedback App in sidebar
=> Sidebar link to feedbackapp

web-gui/src/app/app-routing.module.ts, web-gui/src/app/app.component.ts, web-gui/src/app/app.module.ts, web-gui/src/app/dialogs/goto-links-dialog/goto-links-dialog.component.html, web-gui/src/app/dialogs/goto-links-dialog/goto-links-dialog.component.ts, web-gui/src/app/page-components/course-detail/course-detail.component.html, web-gui/src/app/page-components/course-detail/course-detail.component.ts, web-gui/src/app/page-components/goto/goto.component.ts, web-gui/src/app/page-components/login/login.component.ts, web-gui/src/app/service/feedback-app.service.ts, web-gui/src/app/service/goto.service.ts, ws/src/main/scala/de/thm/ii/fbs/controller/HomeController.scala
This PR add goto Links which can be embeded in external pages to allow fast navigation to the Feedback-System course page and the Feedback-App course session list.
=> Add goto links to fbs course page and fba course page

web-gui/src/app/dialogs/goto-links-dialog/goto-links-dialog.component.html, web-gui/src/app/dialogs/goto-links-dialog/goto-links-dialog.component.scss, web-gui/src/app/dialogs/goto-links-dialog/goto-links-dialog.component.ts, web-gui/src/app/page-components/course-detail/course-detail.component.ts, web-gui/src/app/service/goto.service.ts
This PR adds automatic course join to goto links and adds copy buttons to the goto link dialog.
=> Update goto links

web-gui/src/app/dialogs/goto-links-dialog/goto-links-dialog.component.html
Fixes a missing readonly in the goto link form.
=> Fix goto dialog form readonly

ws/src/main/scala/de/thm/ii/fbs/model/Task.scala, ws/src/main/scala/de/thm/ii/fbs/model/TaskResult.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/CourseResultService.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistance/EvaluationContainerService.scala
Improves the SQL queries of the Course Evaluation Container & the Course Result.
=> Course evaluation improvements

ws/src/main/scala/de/thm/ii/fbs/services/persistance/CourseResultService.scala
=> CourseResult bug fix

ws/src/main/scala/de/thm/ii/fbs/services/persistance/CourseResultService.scala
=> Shifted column names in results

master-runner/src/main/scala/de/thm/ii/fbs/services/DockerService.scala
=> Bash Checker removes new line

web-gui/src/app/page-components/conference/conference.component.html, web-gui/src/app/page-components/conference/conference.component.ts
This PR adds a interval to the user update rate of the conferece to hot fix #534 until a proper solution is found.
=> Reduce conference user refresh interval

web-gui/angular.json, web-gui/package.json, web-gui/proxy.config.json, web-gui/src/app/page-components/results/results.component.html, web-gui/src/app/page-components/results/results.component.scss
highlighting visible submission result + angular proxy
=> Highlight currently presented task result

web-gui/src/app/app-routing.module.ts
=> Redirect logged in users to `/courses`

.github/workflows/ci-cd.yml, .github/workflows/deploy-test-system.yml, ci/restart-feedbacksystem.sh
Automatically deploy push on dev to testsystem via SSH proxy.
=> [CI/CD] Added testsystem Deployment

ci/restart-feedbacksystem.sh
Only pull images that were possibly updated in this repo.
---
Follow up #570
=> [CI/CD] Selectively pull images on test system

web-gui/src/app/page-components/course-detail/course-detail.component.ts
=> Course participation is only displayed after reloading

web-gui/src/app/model/SubTaskStatistic.ts, web-gui/src/app/page-components/course-detail/course-results/results-statistic/results-statistic.component.html, web-gui/src/app/page-components/course-detail/course-results/results-statistic/results-statistic.component.scss, web-gui/src/app/page-components/course-detail/course-results/results-statistic/results-statistic.component.ts
=> Calculation for the rate of edited task added

web-gui/src/app/tool-components/participants/participants.component.ts
resolves #592
---
:warning: Please test with users who do not have admin rights.
=>   Removing users from courses or changing their role is not possible

master-runner/build.gradle, web-gui/build.gradle, web-gui/package-lock.json, ws/build.gradle
=> Remove jcenter and upgrade nodejs version

web-gui/src/app/model/Roles.ts, web-gui/src/app/page-components/user-management/user-management.component.ts, web-gui/src/app/tool-components/participants/participants.component.ts
=> Correct sorting order for course participant roles

web-gui/src/app/page-components/course-detail/course-results/evaluation-results/evaluation-results.component.html
=> Display the same category Names in Point-Editing and Statistics

ws/src/main/scala/de/thm/ii/fbs/services/evaluation/EvaluationResultService.scala, ws/src/test/scala/de/thm/ii/fbs/services/evaluation/EvaluationResultServiceTest.scala
=> Course results are not calculated correctly

swagger.yml, web-gui/src/app/service/course-registration.service.ts, web-gui/src/app/tool-components/participants/participants.component.html, web-gui/src/app/tool-components/participants/participants.component.scss, web-gui/src/app/tool-components/participants/participants.component.ts, ws/src/main/scala/de/thm/ii/fbs/controller/CourseRegistrationController.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistence/CourseRegistrationService.scala
=> Possibility to clean up a course

web-gui/src/app/page-components/course-detail/course-results/results-statistic/results-statistic.component.ts, web-gui/src/app/service/course-results.service.ts, ws/src/main/scala/de/thm/ii/fbs/controller/CourseResultController.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistence/CourseResultService.scala
=> statistics should exclude teachers and tutors

ws/src/main/resources/application.yml, ws/src/main/scala/de/thm/ii/fbs/config/WebConfig.scala, ws/src/main/scala/de/thm/ii/fbs/security/AntiBruteForceInterceptor.scala
=> Add brute force protection

web-gui/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.html, web-gui/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts, web-gui/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts
=> Default values for forms

docker-compose.yml, master-runner/build.gradle, master-runner/src/main/resources/config.json, master-runner/src/main/scala/de/thm/ii/fbs/services/runner/SQLRunnerService.scala, master-runner/src/main/scala/de/thm/ii/fbs/types/SqlRunArgs.scala, master-runner/src/main/scala/de/thm/ii/fbs/types/TaskQuery.scala, master-runner/src/main/scala/de/thm/ii/fbs/util/DBConnections.scala, master-runner/src/main/scala/de/thm/ii/fbs/verticles/runner/SqlRunnerVerticle.scala
In order for the queries to be executed on a Postgresql database, the key `"dbType": "postgresql"` must be added to the `section.json` (the primary file).
---
resolves #638
=> [SQL Checker] Support PostgreSQL queries

docker-compose.yml
Fixes a bug in the Docker Compose file which was introduced by #641.
---
Follow up #641
=> Fix Docker-Compose configuration

web-gui/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.html, web-gui/src/app/dialogs/task-new-dialog/task-new-dialog.component.html, web-gui/src/app/page-components/results/results.component.html, web-gui/src/app/page-components/results/results.component.scss, ws/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala, ws/src/main/scala/de/thm/ii/fbs/model/ExtendedInfoExcel.scala, ws/src/main/scala/de/thm/ii/fbs/model/MediaInformation.scala, ws/src/main/scala/de/thm/ii/fbs/services/checker/CheckerServiceFactoryService.scala, ws/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelCheckerService.scala, ws/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelService.scala, ws/src/main/scala/de/thm/ii/fbs/services/checker/excel/SpreadsheetCheckerService.scala, ws/src/main/scala/de/thm/ii/fbs/services/checker/excel/SpreadsheetService.scala
=> Excel checker

master-runner/src/main/scala/de/thm/ii/fbs/services/runner/SQLRunnerService.scala, master-runner/src/main/scala/de/thm/ii/fbs/util/DBConnections.scala
=> [SQL Checker] Error with too many simultaneous checks

ws/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala, ws/src/main/scala/de/thm/ii/fbs/services/checker/SqlCheckerRemoteCheckerService.scala, ws/src/main/scala/de/thm/ii/fbs/services/checker/trait/CheckerServiceOnMainFileUpload.scala, ws/src/main/scala/de/thm/ii/fbs/services/persistence/CheckerConfigurationService.scala
=> Improve sql-checker creation and localisation

web-gui/src/app/page-components/results/results.component.scss, web-gui/src/app/page-components/results/results.component.ts
=> [Web-GUI] Scrollbar is shown under task tabs in chrome based browsers

ws/src/main/resources/application.yml
=> Clean up backend log output

.github/workflows/ci-cd.yml, .github/workflows/deploy-test-system.yml, ci/docker-deploy.sh
This PR adjusts all CI/CD configurations to the name change.
=> Rename the master branch to main

.github/workflows/ci-cd.yml
=> [CI/CD] Run Dockerhub deployment on main

modules/fbs-core/web/.prettierrc.json
=> [Web] Frontend build fails on windows

modules/fbs-core/web/angular.json, modules/fbs-core/web/build.gradle
=> [API] Frontend build does not copy dist output

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/checker/RunnerConfiguration.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/checker/RunnerRequest.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/checker/SqlCheckerSubmission.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/checker/SqlRunnerSubmission.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/checker/Submission.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/checker/User.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/RemoteCheckerService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/SqlCheckerRemoteCheckerService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/DockerService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/runner/SQLCheckerService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/types/Submission.scala, modules/fbs-sql-checker/api/JSONCreator.py
=> [API] Add mongodb url to sql checker call

modules/fbs-core/api/src/main/resources/privacy_text.md
=> Fix typos in `privacy_text.md`

.github/workflows/add-issue-to-project.yml
=> [CI] Automatically add all new issues to the github Project

modules/fbs-core/web/src/app/page-components/sidebar/sidebar.component.html
=> Remove Github Wiki from the options menu

docker-compose.yml, modules/fbs-core/api/Dockerfile, modules/fbs-runner/checker/Dockerfile, runtime-images/bash/Dockerfile
=> [Docker] Dockerfile and healthcheck improvements

modules/fbs-core/api/api-docs.yml, modules/fbs-core/api/src/main/resources/migrations/04_task_deadline_null.sql, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/SubmissionController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/Task.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/TaskService.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/evaluation/EvaluationResultServiceTest.scala
=> [API] Allow unspecified Deadlines for Tasks

modules/fbs-core/web/src/app/page-components/sidebar/sidebar.component.html, modules/fbs-core/web/src/app/page-components/sidebar/sidebar.component.scss
=> Link Logo to start page

modules/fbs-core/web/src/app/app.module.ts, modules/fbs-core/web/src/app/dialogs/text-confirm-dialog/text-confirm-dialog.component.html, modules/fbs-core/web/src/app/dialogs/text-confirm-dialog/text-confirm-dialog.component.ts, modules/fbs-core/web/src/app/tool-components/participants/participants.component.ts
=> Improve dialogues for deleting all users

modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.ts
=> No loading bar is displayed during a file upload for a submission

modules/fbs-sql-checker/api/JSONCreator.py, modules/fbs-sql-checker/api/Main.py, modules/fbs-sql-checker/api/TableChecker.py
=> I774 fix error where attempt and statement are swapped

modules/fbs-core/api/api-docs.yml, modules/fbs-core/api/src/main/resources/migrations/06_task_requirement_type.sql, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/Task.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/TaskService.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/evaluation/EvaluationResultServiceTest.scala
=> [API] Mark tasks as mandatory bonus/additional etc

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelService.scala
=> The Excel shows an error for some of the deliveries although they are actually correct

.dockerignore, .github/workflows/ci-cd.yml, docker-compose.yml, modules/fbs-core/api/Dockerfile, modules/fbs-runner/checker/Dockerfile
=> [Docker] Improve Dockerfile build process

modules/fbs-core/api/Dockerfile
=> [Docker] Fix missing frontend build

modules/fbs-core/web/package-lock.json, modules/fbs-core/web/package.json, modules/fbs-core/web/src/app/app.module.ts
=> Deadline: Change date format to European

modules/fbs-core/web/src/app/app-routing.module.ts, modules/fbs-core/web/src/app/app.module.ts, modules/fbs-core/web/src/app/page-components/sidebar/sidebar.component.html, modules/fbs-core/web/src/app/page-components/sql-playground/sql-playground.component.ts
resolves #778 
I couldn't find the "test tube" icon shown in the mock up. Instead I used a puzzle icon, which fits with the "playground". Tell me, whether this is fine or not.
=> add navbar item with empty page

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala, modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.html, modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts, modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts, modules/fbs-core/web/src/app/enums/checkerFileType.ts, modules/fbs-core/web/src/app/page-components/configuration-list/configuration-list.component.ts, modules/fbs-core/web/src/app/service/checker.service.ts, modules/fbs-core/web/src/app/tool-components/dropzone/dropzone.component.ts
There are still some issues with the validation of the files.
To close this topic for the time being, I have created another issue. See: #825
resolves #766
=> Fix editing task check configurations

.github/workflows/fbs-core-api.yml, scripts/ci/validate-migrations.sh
=>  [CI/CD] Migration should only be able to be added in sequence

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/MediaInformation.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelCheckerService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelService.scala
=> [Excel-Checker] It should be possible to define multiple output fields

modules/fbs-core/api/api-docs.yml
=> [API] Fixes discrepancy in API documentation

scripts/analysis/excel/analyze.ipynb, scripts/analysis/excel/analyze_code.py
added requirements given in issue and extended analysis
closes #777
=> [Excel-Checker] Further analysis of the existing Excel submissions

modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.ts
The error was caused by the change in https://github.com/thm-mni-ii/feedbacksystem/commit/d2ba55ffbcfece3ab2bf09f32c2c0052e1b2e1ff#diff-3aad0bd84e8267fad1f00169fc576a07aade726d7e1fdd92e2008368c50a5c22
---
resolves #862
=> [Web] Frontend does not upload the selected file

scripts/ci/docker-deploy.sh
=> [CI] Fixing errors in the sql-checker deployment

modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.html, modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts, modules/fbs-core/web/src/app/page-components/configuration-list/configuration-list.component.ts, modules/fbs-core/web/src/app/page-components/subtask-results/subtask-results.component.ts, modules/fbs-core/web/src/app/service/checker.service.ts, modules/fbs-core/web/src/app/service/task.service.ts
=> runner configuration files

modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts
=> Checkers not showing after creation

scripts/analysis/excel/analyze_code.py
=> [Exel-Checker] Improve Reusability

docker-compose.yml
=> [Docker] Pins image versions in docker compose

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/CourseRegistrationService.scala
=> Tasks are not loaded for users that are not in the course

modules/fbs-core/api/api-docs.yml, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CourseController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/SemesterController.scala
=> Updating the course semester ID does not work

modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/DockerService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/runner/SQLCheckerService.scala
=> [Runner] Improve checker environment support

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/CourseResultService.scala
=> [API] Sort course results alphabetically

docker-compose.yml, modules/fbs-runner/checker/src/main/resources/config.json, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/MainVerticle.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/ExtendedResultsService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/db/DBOperationsService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/db/MySqlOperationsService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/db/PsqlOperationsService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/runner/SQLPlaygroundService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/runner/SQLRunnerService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/types/Database.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/types/OutputJsonStructure.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/types/SqlPlaygroundRunArgs.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/util/DBConnections.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/util/DBTypes.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/util/DatabaseInformationService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/util/PlaygroundDBConnections.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/util/ResultSetIterator.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/util/Secrets.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/util/SqlPlaygroundMode.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/verticles/HttpVerticle.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/verticles/runner/SqlPlaygroundVerticle.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/verticles/runner/SqlRunnerVerticle.scala
=> Extension of the SQL Checker to cover persistent databases

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/checker/excel/SpreadsheetCell.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/CheckerServiceFactoryService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelCheckerService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/SpreadsheetFileService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetCheckerService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetService.scala
=> [Excel-Checker] Refactor ExcelCheckerService

modules/fbs-core/web/src/app/app.module.ts, modules/fbs-core/web/src/app/model/sql_playground/Database.ts, modules/fbs-core/web/src/app/page-components/sidebar/sidebar.component.html, modules/fbs-core/web/src/app/page-components/sql-playground/db-control-panel/db-control-panel.component.html, modules/fbs-core/web/src/app/page-components/sql-playground/db-control-panel/db-control-panel.component.scss, modules/fbs-core/web/src/app/page-components/sql-playground/db-control-panel/db-control-panel.component.ts, modules/fbs-core/web/src/app/page-components/sql-playground/db-control-panel/test-data/databases.json, modules/fbs-core/web/src/app/page-components/sql-playground/sql-playground.component.html, modules/fbs-core/web/src/tsconfig.app.json
=> implement DB controll component

modules/fbs-core/api/src/main/resources/migrations/09_sql_playground_use_correct_datatype.sql
=> [SQL Playground] Error while storing larger Database Informations

modules/fbs-core/api/api-docs.yml
=> docs(SQL Playground api): fix database creation method

scripts/analysis/excel/analyze_code.py
=> [Exel-Checker] Result visualization

modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/controller/v2/RunnerApiController.kt
=> [SQL Playground] The database information is deleted if the query returns an error

modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/checker/RemoteCheckerV2Service.kt
=> [SQL Playground] Error while executing SQL statements with special chars 

modules/fbs-core/api/src/main/resources/migrations/10_sql_playground_fix_statement_data_type.sql
=> [SQL Playground] Error while storing larger SQL statements

modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/controller/v2/PlaygroundController.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/controller/v2/RunnerApiController.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/model/v2/playground/SqlPlaygroundDatabase.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/persistence/SqlPlaygroundDatabaseRepository.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/persistence/SqlPlaygroundEntityRepository.kt, modules/fbs-core/api/src/main/resources/migrations/11_sql_playground_soft_delete_databases.sql
:warning:  `404` is still returned for existing databases. An empty array is only returned for new databases.
---
resolves #969 
resolves #970
=> [SQL Playground] Add soft deletion of playground database and auto creation of playground entities

modules/fbs-core/api/api-docs.yml, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/db/PsqlOperationsService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/runner/SQLPlaygroundService.scala
=> [SQL Playground] Improve the `table/view/trigger/routines`-Routes Data types

.github/release.yml, chart/Chart.yaml
Updates the App version used in the Helm Chart to the newest version
=> [Helm] Update App version to 1.3.0

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetCheckerService.scala
=> [Math-Checker] Fix string comparision

modules/fbs-core/web/src/app/page-components/login/login.component.ts
resolves #494 
I can't test it locally. So we'll see, if the bug is fixed or not...
=> Logout does not work in the approx. 10 seconds after login.

modules/fbs-core/web/src/app/dialogs/course-update-dialog/course-update-dialog.component.html, modules/fbs-core/web/src/app/dialogs/course-update-dialog/course-update-dialog.component.scss, modules/fbs-core/web/src/app/dialogs/course-update-dialog/course-update-dialog.component.ts, modules/fbs-core/web/src/app/model/Semester.ts, modules/fbs-core/web/src/app/service/semester.service.ts
=> [Web] Add semester field to courses and auto archive old courses

modules/fbs-core/api/api-docs.yml, modules/fbs-core/api/build.gradle, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerApiController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CourseController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/ExportController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/ResultController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/SubmissionController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/exception/InternalServerException.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/CheckrunnerConfiguration.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/CheckrunnerSubTask.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/SqlCheckerRemoteCheckerService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/export/TaskExportService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/CheckrunnerConfigurationService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/CheckrunnerSubTaskService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/util/Archiver.scala
=> [API] Export functionality for single tasks

modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.html, modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts, modules/fbs-core/web/src/app/model/Task.ts, modules/fbs-core/web/src/app/page-components/course-detail/course-detail.component.html, modules/fbs-core/web/src/app/page-components/course-detail/task-preview/task-preview.component.html, modules/fbs-core/web/src/app/page-components/course-detail/task-preview/task-preview.component.scss
=> [Web] show tasks only for lecturers tutors

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetService.scala
=> [Mathe-Checker] remove rounding of math checker input values

modules/fbs-core/web/src/app/page-components/sql-playground/dynamic-result-table/dynamic-result-table.component.ts
=> fix duplicate column bug

modules/fbs-core/web/src/app/page-components/sql-playground/db-scheme/db-scheme-tables/db-scheme-tables.component.html, modules/fbs-core/web/src/app/page-components/sql-playground/db-scheme/db-scheme-tables/db-scheme-tables.component.ts, modules/fbs-core/web/src/app/page-components/sql-playground/sql-playground.component.html, modules/fbs-core/web/src/styles.scss
=> show table data with button click

chart/Chart.yaml, chart/values.yaml
Updates the App version used in the Helm Chart to the newest version
=> [Chart] Update App version to 1.4.0

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetService.scala
=> [Math-Checker] Prevent error when setting empty cells

modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts, modules/fbs-core/web/src/app/page-components/course-detail/course-detail.component.html, modules/fbs-core/web/src/app/page-components/course-detail/task-preview/task-preview.component.html
=> Tasks are not displayed to students

.github/workflows/deploy-test-system.yml
=> ci(deploy-test-system): wait until Docker image is deployed

modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/model/v2/checker/excel/Cell.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/checker/excel/PropagatedErrorsService.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/utils/v2/spreadsheet/SpreadsheetReferenceParser.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/utils/v2/spreadsheet/SpreadsheetValueParser.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/services/v2/checker/excel/PropagatedErrorsServiceTest.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/utils/v2/spreadsheet/SpreadsheetReferenceParserTest.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/utils/v2/spreadsheet/SpreadsheetTestUtils.kt
=> [Excel-Checker] Propagated errors analysis

.github/problem-matchers/java.json, modules/fbs-core/api/build.gradle, modules/fbs-runner/checker/build.gradle
=> [CI] Include Kotlin in Coverage Report

modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/model/v2/checker/excel/ReferenceGraph.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/checker/excel/PropagatedErrorsService.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/model/v2/checker/excel/ReferenceGraphTest.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/services/v2/checker/excel/PropagatedErrorsServiceTest.kt
=> [Excel-Checker] Optimize error analysis for input cells

modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.html, modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts
=> After changing the task Media type, the validation will not be reset

modules/fbs-core/api/api-docs.yml, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/Task.scala
=> [API] add requirementType practice

modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.html, package-lock.json
input field for date time picker is now read only. copy paste is not allowed. It's just an interim solution untill we implement another solution.
resolves #882
=> Date Time Picker Bug

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/storageBucketName.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelCheckerService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/SpreadsheetFileService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetCheckerService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/MinioService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/StorageService.scala
=> [Minio] Invalid file encoding when reading configuration files

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/TaskService.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/persistence/TaskServiceTest.scala
=> [Core] Task Api contains invalid attempts response 

modules/fbs-core/api/Dockerfile, modules/fbs-runner/checker/Dockerfile
=> [Docker] Switch openjdk images to eclipse-temurin

modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.html, modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.scss, modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts, modules/fbs-core/web/src/app/model/Task.ts, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.html, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.scss, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.ts
=> [WEB] limit the number of submissions 

modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/handler/context/ErrorAnalysisContext.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/checker/excel/PropagatedErrorsService.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/handler/HandlerService.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/utils/v2/handler/Handle.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/utils/v2/handler/Handler.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/utils/v2/handler/When.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/handler/TestHandlers.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/services/v2/checker/excel/HandlerServiceTest.kt
=> [Excel-Chekcer] Add handlers to extend the functionality of the excel checker

modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.html, modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.scss, modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts, modules/fbs-core/web/src/app/model/Task.ts, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.html, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.scss, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.ts
Reverts thm-mni-ii/feedbacksystem#1131 becaus of breakage of existing tasks.
=> Revert "[WEB] limit the number of submissions"

.github/workflows/check-fbs-module.yml, docker-compose.test.yml, modules/fbs-core/api/src/test/resources/application-test.yml, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetCheckerServiceTest.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/evaluation/EvaluationResultServiceTest.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/evaluation/FormulaServiceTest.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/persistence/CourseServiceTest.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/persistence/SubmissionServiceTest.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/persistence/TaskServiceTest.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/security/LocalLoginServiceTest.scala
=> [API] Different database and minio port for tests

modules/fbs-core/math-parser/src/main/antlr/de/thm/ii/fbs/mathParser/Math.g4, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/AstBuilder.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/MathParserHelperTest.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/SemanticAstComparatorTest.kt
=> [Mathe-Checker] Precedence bug multiplication/exponents

modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/checker/excel/ErrorAnalysisService.kt, modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/utils/v2/spreadsheet/SpreadsheetUtils.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/services/v2/checker/excel/ErrorAnalysisServiceTest.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/utils/v2/spreadsheet/SpreadsheetReferenceParserTest.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/utils/v2/spreadsheet/SpreadsheetTestUtils.kt, modules/fbs-core/api/src/test/kotlin/de/thm/ii/fbs/utils/v2/spreadsheet/SpreadsheetUtilsTest.kt
=> [Excel-Checker] Handle null cells

modules/fbs-core/web/src/app/page-components/sql-playground/db-control-panel/db-control-co-working/db-control-co-working.component.ts, modules/fbs-core/web/src/app/page-components/sql-playground/db-control-panel/db-control-db-overview/db-control-db-overview.component.ts
resolves #1142 
in order to see the changes one should delete the previous "Standard Datanbank" database.
=> Typo: SQL Playground

modules/fbs-core/api/src/main/resources/migrations/16_hide_Submission_result.sql, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/SubmissionController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/Submission.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/model/Task.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/SubmissionService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/TaskService.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/persistence/SubmissionServiceTest.scala
=> [API] Configuration to hide the Submission result from the Student

modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.html, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.scss, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.ts
=> button to move to next task

modules/fbs-core/web/src/app/tool-components/participants/participants.component.scss
=> [WEB] Arrange items per page selection correctly

modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.html, modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.ts
=> [WEB] Jump to the newly created tab in the SQL Playground

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/SqlCheckerRemoteCheckerService.scala
=> [API] Repair sql-checker creation

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/ExcelCheckerService.scala
=>   The additional information for Excel tasks is reversed

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/SqlCheckerRemoteCheckerService.scala
=> [API] Pass sql-runner extinfo in sql-checker

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/SqlCheckerRemoteCheckerService.scala
=> [API] Repair SQL remote checker service not working with missing ext info

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/SqlCheckerRemoteCheckerService.scala, modules/fbs-core/web/src/app/page-components/results/results.component.html, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/runner/SQLRunnerService.scala, modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/verticles/runner/SqlRunnerVerticle.scala
> **Warning**
> ~~Merge only after #1275~~
---
closes #1276
=> [Checker] Improve syntax error messages

docker-compose.yml, modules/fbs-core/api/build.gradle, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/config/SecurityConfig.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/health/DatabaseHealthService.scala
=> [Core] Add health check

modules/fbs-core/web/src/app/dialogs/all-submissions/all-submissions.component.html, modules/fbs-core/web/src/app/dialogs/all-submissions/all-submissions.component.ts, modules/fbs-core/web/src/app/page-components/course-detail/course-results/course-results.component.ts, modules/fbs-core/web/src/app/page-components/results/results.component.html, modules/fbs-core/web/src/app/page-components/results/results.component.scss, modules/fbs-core/web/src/app/page-components/results/results.component.ts, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.html, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.ts, modules/fbs-core/web/src/app/service/submission.service.ts
=> Submission in result table is only displayed correctly for sql 

modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/highlighted-input/highlighted-input.component.ts, modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.ts
=> fixed tab content formatting on refresh or change

modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/highlighted-input/highlighted-input.component.ts
=> fixed keyword highlight

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/storage/FsStorageService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/storage/StorageService.scala
=> [Core] Do not delete local files

modules/fbs-core/web/proxy.config.json
=> adjust proxy target

.github/labeler.yml, .github/workflows/labeler.yml
=> [CI] Adds automated labeling for pull requests

.github/labeler.yml, .github/workflows/labeler.yml
=> [CI] Fix labeler paths

.github/actions/retry-codecov/action.yml, .github/workflows/check-fbs-module.yml
=> [CI] Retry codecov on failure

.github/actions/retry-codecov/action.yml
=> ci(retry-codecov): increase wait time between retries

modules/fbs-core/web/src/app/dialogs/new-checker-dialog/new-checker-dialog.component.ts
=> fixed state of sql checker configuration

modules/fbs-core/api/build.gradle, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/MinioService.scala
**The following updates are included in this PR:**
- [update spring boot to 2.7.12](https://github.com/thm-mni-ii/feedbacksystem/commit/adf61168591726f7396284739c38768db6d93a25)
- [update minio to 8.5.3](https://github.com/thm-mni-ii/feedbacksystem/commit/d06fcf616ff325b2ed3418c7c130c905097f28d1)
- [update org.json to 20230618](https://github.com/thm-mni-ii/feedbacksystem/commit/d909ea7a32b50122c341345ac575c8c3a91f6585)
- [update tika to 2.8.0](https://github.com/thm-mni-ii/feedbacksystem/commit/a21f69fee0b98de5150c60b053cbb4305126efff)
=> chore(deps): update multiple gradle dependencies

.github/actions/retry-codecov/action.yml
=> ci(retry-codevoc): not fail ci if first steps fail

modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.ts
=>  remove the emerging blank-page when leaving the sqlplayground route

modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.html, modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.ts, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.html, modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.ts, modules/fbs-core/web/src/app/service/checker.service.ts
=> disabled submission button when no checker provided

modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/highlighted-input/highlighted-input.component.ts
Reverts thm-mni-ii/feedbacksystem#1322
---
resolves #1369 
reopens #1321
=> Revert "fixed keyword highlight"

modules/fbs-eat/eat/api/analysis/analysis.py, modules/fbs-eat/eat/api/dashboard/dashboard.py, modules/fbs-eat/eat/api/data_table/table.py, modules/fbs-eat/eat/api/util/analysis_util.py, modules/fbs-eat/eat/api/util/dashboard_util.py, modules/fbs-eat/eat/api/util/utilities.py
Improved code and fixed minor bugs
=> [EAT] Improve code style

modules/fbs-eat/eat/api/analysis/analysis.py, modules/fbs-eat/eat/api/connect/data_service.py, modules/fbs-eat/eat/api/dashboard/dashboard.py
Decreased time it takes to load the page when handling larger amouts of data
=> [EAT] reduced time to convert dataframes to JSON

modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.html, modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts, modules/fbs-core/web/src/app/page-components/task-detail/submission-spreadsheet/submission-spreadsheet.component.html, modules/fbs-core/web/src/app/page-components/task-detail/submission-spreadsheet/submission-spreadsheet.component.scss, modules/fbs-core/web/src/app/tool-components/math-input/math-input.component.html, modules/fbs-core/web/src/app/tool-components/math-input/math-input.component.scss, modules/fbs-core/web/src/app/tool-components/math-input/math-input.component.ts, modules/fbs-core/web/src/app/util/css.ts
=>  [WEB] fix width of math task

modules/fbs-core/math-parser/src/main/antlr/de/thm/ii/fbs/mathParser/Math.g4, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/AstBuilder.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/MathParserHelper.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/ast/Operator.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/marshal/MathJsonMarshal.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/transformers/CommutativeLawTransformer.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/MathParserHelperTest.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/SemanticAstComparatorTest.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/marshal/MathJsonMarshalTest.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/marshal/MathJsonUnmarshalTest.kt
=> [Math] Add support for equations

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetCheckerService.scala, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetService.scala, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/AstBuilder.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/MathParserHelper.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/SemanticAstComparator.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/ast/Operator.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/ast/Text.kt, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/marshal/LatexMarshal.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/MathParserHelperTest.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/marshal/LatexMarshalTest.kt, modules/fbs-core/web/src/app/page-components/task-detail/submission-spreadsheet/submission-spreadsheet.component.html
=> [Math-Checker] Use latex instead of MathJson

modules/fbs-core/web/src/app/tool-components/math-input/math-input.component.ts
=>  [WEB] remove vertical scrollbar on math task 

modules/fbs-core/web/src/app/model/sql_playground/QueryTab.ts, modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/highlighted-input/highlighted-input.component.html, modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/highlighted-input/highlighted-input.component.scss, modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.html, modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.scss, modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.ts, modules/fbs-core/web/src/styles.scss
resolve #1384 
@TimonPllkrn 
Unfortunately it is not possible to place the button properly next to the tabs.
Unfortunately there always remains a white border on the right side -> See Fig 1.
So I have changed the tab control a little bit. See figure. At the moment it does not look 100% beautiful, which is probably due to familiarity. However, in the future, more implementations of new features are easily possible.
If you prefer the first option we can also take this one
=> remove all tabs in playground

modules/fbs-core/api/src/main/resources/migrations/18_unique_username.sql, modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/UserController.scala, modules/fbs-core/api/src/test/scala/de/thm/ii/fbs/services/security/LocalLoginServiceTest.scala, modules/fbs-core/web/src/app/page-components/user-management/user-management.component.ts
=> [Core] Add unique constraint to username

docker-compose.yml
=> [Docker] Add new db called psql-sharing

modules/fbs-core/web/src/app/page-components/task-detail/task-detail.component.html
=> [I18N] Do not display translation key as tooltip for task navigation buttons

modules/fbs-core/math-parser/src/main/antlr/de/thm/ii/fbs/mathParser/Math.g4, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/AstBuilder.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/SemanticAstComparatorTest.kt
=> [Math-Checker] Resolve problem with frac and unary minus

modules/fbs-core/math-parser/src/main/antlr/de/thm/ii/fbs/mathParser/Math.g4, modules/fbs-core/math-parser/src/main/kotlin/de/thm/ii/fbs/mathParser/AstBuilder.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/MathParserHelperTest.kt, modules/fbs-core/math-parser/src/test/kotlin/de/thm/ii/fbs/mathParser/SemanticAstComparatorTest.kt
=> [Math-Parser] Support Unicode exponents

modules/fbs-runner/checker/src/main/scala/de/thm/ii/fbs/services/db/PsqlOperationsService.scala
The command is working now.
`postgresql://user:password@127.0.0.1:8432/database`
=> [Runner] Modified writeQuery to make the dump works without issues

modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/HomeController.scala, modules/fbs-core/web/src/app/page-components/fbs-modelling/fbs-modelling.component.ts
=> [API] Add modelling to home controller routes

modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/highlighted-input/highlighted-input.component.scss, modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/highlighted-input/highlighted-input.component.ts
=> [Playground ] insert sql code from power point to playground

modules/fbs-core/web/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts
=> fix new task bug

modules/fbs-core/web/src/app/page-components/sql-playground/db-scheme/db-scheme-routines/db-scheme-routines.component.html
=> [Playground] Only display parameters where available

modules/fbs-core/web/src/app/page-components/fbs-modelling/fbs-modelling.component.ts, modules/fbs-core/web/src/app/page-components/sidebar/sidebar.component.html, modules/fbs-core/web/src/app/page-components/sidebar/sidebar.component.ts
=> adjust modelling tool i-frame

.github/workflows/ci.yml, scripts/ci/docker-deploy.sh
=> fix(ci): rename docker-compose to docker compose

modules/fbs-core/web/src/app/page-components/sql-playground/db-control-panel/state/databases.effects.ts, modules/fbs-core/web/src/app/page-components/sql-playground/db-control-panel/state/groups.effects.ts
=> fix(playground): fix race condition in sql playground loading

modules/fbs-qcm/web/src/App.vue, modules/fbs-qcm/web/src/router/index.ts, modules/fbs-qcm/web/src/services/study.service.ts, modules/fbs-qcm/web/src/views/CatalogOverview.vue, modules/fbs-qcm/web/src/views/HomeView.vue
=> [QCM] refactor home view
